#!/usr/bin/env python3

opgave = """
QVGQVGQVGQVGQVGQVGQVGQNGQNGQNGQNGQNGQNGQVGQVGQVGQNGQVGQVGQNG
QVGQVGQNGQVGQVGQVGQVGQNGQVGQVGQVGQVGQVGQVGQVGQNGQNGQNGQNGQNG
QVGQNGQNGQNGQVGQNGQVGQNGQVGQNGQVGQNGQNGQVGQVGQVGQNGQVGQVGQVG
QNGQVGQVGQVGQNGQVGQNGQNGQVGQVGQVGQVGQVGQNGQNGQNGQVGQVGQNGQNG
QNGQVGQVGQVGQVGQVGQVGQVGQVGQVGQVGQVGQNGQNGQVGQVGQNGQNGQNGQVG
QNGQNGQNGQVGQVGQNGQNGQVGQVGQNGQVGQVGQVGQVGQNGQVGQNGQNGQVGQNG
QVGQNGQNGQVGQVGQVGQVGQVGQNGQNGQNGQNGQVGQNGQVGQNGQNGQNGQNGQNG
QVGQVGQNGQVGQNGQVGQVGQNGQVGQVGQVGQNGQNGQNGQNGQVGQVGQVGQNGQNG
QVGQVGQNGQVGQVGQNGQNGQVGQNGQVGQVGQVGQVGQVGQNGQVGQVGQNGQNGQVG
""".strip()
LEN=len(opgave.split('\n')[0])
for columnNr, i in enumerate(range(0, LEN, 3)):
    #if columnNr % 2 == 0: print('|', end='')
    for rowNr, l in enumerate(opgave.split('\n')):
        #if rowNr % 3 == 0: print('-'*(LEN//2))
        a,b,c = l[i:i+3]
        assert a == 'Q' and b in 'NV' and c == 'G'
        print(' ' if b != 'N' else '\u25a0', end=' ')
    print()
